apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:                         # Init container
        - name: init-sleep
          image: busybox
          command: ['sh', '-c', 'echo "Initializing..."; sleep 10']
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          livenessProbe:                     # Liveness Probe
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:                    # Readiness Probe
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

